### ISSUE TITLE
Linediff specific diffopts 

### ISSUE THREAD

**Issue by yohan-pereira** [AndrewRadev/linediff.vim#21]
It would be nice if we could specify diffopts that apply only for linediff (like iwhite). 

something like linediff_diffopt += iwhite

**Comment by AndrewRadev** [comment]
This does make sense, but as far as I can tell, `diffopt` is a global option. The only way I can see this working is if I set the value before starting the linediff, and then resetting it to its previous value when done. Also, it wouldn't be possible to use `+=`, since that syntax works only for the `:set` command, but doesn't work for ordinary variables. You'd have to `let g:linediff_diffopt = 'filler,iwhite'` (for example) to get it to work.

That said, I've pushed a commit that implements this. Let me know if it works for you.

**Comment by AndrewRadev** [comment]
Since I've implemented this, and it seems to work for me, I'll close this issue for now. Let me know if you have different ideas on how it should work.
