### ISSUE TITLE
Doesn't work with different source files.

### ISSUE THREAD

**Issue by niloct** [AndrewRadev/linediff.vim#22]
I have Linediff installed with latest Vundle, in Mac OS X, vim 8.0, and when I issue `:Linediff` in the second block of text (on second file), the diff window appears with the left buffer totally empty, in red...

**Comment by niloct** [comment]
```
set nocompatible "Required by Vundle
filetype off "Required by Vundle
set rtp+=~/.vim/bundle/Vundle.vim/
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'AndrewRadev/linediff.vim'

" All of your Plugins must be added before the following line
call vundle#end()            " required

filetype plugin indent on    " required
```
I issued a complete reinstall of Vundle plugins leaving only linediff in the above `.vimrc`. It still won't work.

**Comment by niloct** [comment]
Different blocks in same buffer do work.

**Comment by xaizek** [comment]
Tried your configuration, everything works fine with single/multiple buffers. I ran Vim as `vim -u tmp-vimrc`, so if you don't have any system-wide settings, setup should be the same.

**Comment by niloct** [comment]
Have you tried on a Mac ? I'm using iTerm2, installed original iTerm to test, see attached gif please.
![linediff](https://cloud.githubusercontent.com/assets/1529383/19611642/69e81ce6-97c1-11e6-9875-1f43c35449b9.gif)

**Comment by xaizek** [comment]
I'm on GNU/Linux, terminal shouldn't matter. Actually I managed to reproduce it this time, your gif helped. Before I used `:tabedit` or `:vs` and it worked, if I do `:edit` for the second file, it doesn't work (with this configuration, the one I usually use works fine either way). So far have no idea, why it works this way, but it's not just your local problem.

**Comment by xaizek** [comment]
@niloct, it's not something you have in your `vimrc`, it's something you don't have there. Try adding:
```vim
set hidden
```
Looks like `getbufline()` function doesn't return lines from buffers which aren't hidden. And this is probably *not* a bug, because if buffer disappears from all windows and `'hidden'` isn't set, that buffer gets unloaded.

**Comment by niloct** [comment]
Thanks for the great tip. It worked. So I misunderstood the help when it says that a buffer displayed in another window (other than current) does not get hidden. It gets unloaded then, without the option `set hidden`.

**Comment by xaizek** [comment]
> a buffer displayed in another window (other than current) does not get hidden.

That's correct statement. In the gif above you have only one window, each window displays only one buffer, so when you do `:e y.txt` `x.txt` gets unloaded and `y.txt` is loaded. If `x.txt` were still visible in another tab or split window, then it would still be loaded.

**Comment by niloct** [comment]
Awesome! Thanks again :)

**Comment by AndrewRadev** [comment]
Thanks, @xaizek, for debugging the issue, I really appreciate your help :).

It does make sense that, if `set hidden` is not on, the buffer would be lost. I'll try and see if there's a way to set "bufhidden" on a buffer that has been linediffed, and then restore it to its default, but it might be a bit tricky to juggle the value. For now, I think I'll put a comment in the documentation, at least.

**Comment by AndrewRadev** [comment]
I think I may have fixed it, actually. Turns out it's not so complicated to save and restore the value :). However, the first buffer remains hidden (it was closed, after all), and if that first buffer's content has been changed, you can't quit -- Vim asks you to save all of your changes. But I think that might be fine, after all, you've closed this buffer, and are now making changes to it, I guess it's to be expected that Vim prompts you to finish up.

@niloct, if you'd like to test the behaviour of the plugin without the `set hidden` option, I'd appreciate it, just so I know if what I did avoids this issue now.

**Comment by xaizek** [comment]
> Thanks, @xaizek, for debugging the issue, I really appreciate your help :).

It was bothering me for a while that I didn't figure this one out back then.
@boo1ean look, after some 4 years I know what didn't work in your setup :-)

> just so I know if what I did avoids this issue now.

Seems to work for me in test configuration.

**Comment by niloct** [comment]
Glad to have been part of this brainstorming. It is working for me too, without the `set hidden` option!

**Comment by AndrewRadev** [comment]
Cool, thanks. I'll remove the comment in the documentation then.
