### ISSUE TITLE
Undo changes

### ISSUE THREAD

**Issue by nkgm** [AndrewRadev/linediff.vim#24]
Undo seems to clear buffer contents regardless of previous edits. Is that something to be avoided?

**Comment by AndrewRadev** [comment]
The way the plugin works is:

- A new empty buffer is opened
- The relevant lines from the original buffer are added

The initial undo point comes from the fact that the opened buffer is brand new.

Thankfully, since the plugin uses, by default, a tempfile to store the contents, I was able to just add the lines to the file before opening it. Right now, undoing shouldn't clear buffer contents, as long as `g:linediff_buffer_type` is at its default value of "tempfile". Could you try it out and see if it feels right to you?

If you set `g:linediff_buffer_type` to "scratch", this can't work, since there's no way (that I know of) to pre-set the contents of the scratch buffer. Also note that undoing can't be "transplanted" from the original buffer, since the proxy buffers are brand new and have their own history.

**Comment by xaizek** [comment]
Instead of avoiding changes one could clear undo history after performing a set of changes, which should work for all kinds of buffers. [`:h clear-undo`](http://vimhelp.appspot.com/undo.txt.html#clear-undo) provides a snippet to do just that.

**Comment by AndrewRadev** [comment]
Nice, I wasn't aware of this trick! It seems a bit hacky to me, but it looks like it does the job. I've implemented it for the "scratch" buffer type as well (no need to rollback the `writefile`, I think, it does seem like a nicer way to fill the temp file with contents). Thanks, @xaizek!

So now, @nkgm, an undo shouldn't clear the buffer contents in any situation.

**Comment by nkgm** [comment]
Works great. Thanks @xaizek and thank you @AndrewRadev for this great plugin.
